// Vérifie supabase-fiche-retours.sql sur un vrai moteur Postgres (PGlite). Usage : node tests/sql-fiche-retours.check.mjs
import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
const db = new PGlite();
await db.exec(`
create schema auth; create role anon; create role authenticated;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('app.uid', true),'')::uuid $$;
create table public.agent_fiches(agent_user_id uuid, filename text);
grant usage on schema public, auth to anon, authenticated; grant select on public.agent_fiches to authenticated;
insert into public.agent_fiches values ('11111111-1111-1111-1111-111111111111','a-FINAL.html'),('22222222-2222-2222-2222-222222222222','b-FINAL.html');`);
const rd = f => fs.readFileSync(new URL('../' + f, import.meta.url), 'utf8').split('-- Rétention : suppression automatique après 12 mois (à exécuter')[0];
const sql = rd('supabase-fiche-retours.sql');
await db.exec(sql); await db.exec(`grant select, delete on public.fiche_retours to authenticated;`);
let bad = 0; const ok = (c, m) => { if (!c) { console.log('ÉCHEC', m); bad++; process.exitCode = 1; } else console.log('ok', m); };
const call = (p, c, rep, lang = 'fr') => db.query(`select public.fiche_retour($1,$2,'adr',null,$3::text[],$4)`, [p, c, rep, lang]);
const count = async (w = '') => (await db.query(`select count(*)::int n from public.fiche_retours ${w}`)).rows[0].n;
await call('/fiches/a-FINAL.html', 'Marie', ['prix', 'travaux', 'prix', 'pirate', '<script>', 'quartier', 'charges', 'agencement']);
const r = (await db.query(`select * from public.fiche_retours`)).rows[0];
ok(await count() === 1 && r.reponses.length === 4 && r.reponses.every(x => ['prix', 'travaux', 'quartier', 'charges', 'agencement'].includes(x)), 'liste fermée, dédoublonnage, 4 max : ' + JSON.stringify(r.reponses));
ok(r.agent_id === '11111111-1111-1111-1111-111111111111', 'agent_id lu en base (le paramètre p_agent est ignoré)');
await call('/fiches/inconnue.html', 'Marie', ['prix']); await call('/x/a-FINAL.html', 'Marie', ['prix']); await call('/fiches/a-FINAL.html', 'Marie', []); await call('/fiches/a-FINAL.html', 'Marie', ['pirate']);
ok(await count() === 1, 'fiche inconnue / chemin invalide / vide / codes inconnus refusés');
let denied = false; try { await db.query(`insert into public.fiche_retours(fiche_path, reponses) values ('/fiches/a-FINAL.html', '{texte libre}')`); } catch (e) { denied = true; } ok(denied, 'le CHECK de la table refuse un texte libre même en insertion directe');
await call('/fiches/a-FINAL.html', 'Marie', ['prix'], 'xx'); ok((await db.query(`select lang from public.fiche_retours order by created_at desc limit 1`)).rows[0].lang === null, 'langue inconnue → null');
for (let i = 0; i < 10; i++) await call('/fiches/a-FINAL.html', 'Marie', ['prix']);
ok(await count(`where client_nom='Marie'`) === 3, '3 retours max / 10 min par acquéreur : ' + await count());
for (let i = 0; i < 100; i++) await call('/fiches/b-FINAL.html', 'Faux' + i, ['prix']);
ok(await count(`where fiche_path='/fiches/b-FINAL.html'`) === 40, 'plafond 40/h par fiche malgré noms variables');
await db.exec(`set role anon`);
denied = false; try { await db.query('select * from public.fiche_retours'); } catch (e) { denied = true; } ok(denied, 'anon : lecture directe refusée');
denied = false; try { await db.query(`insert into public.fiche_retours(fiche_path,reponses) values ('/fiches/a-FINAL.html','{prix}')`); } catch (e) { denied = true; } ok(denied, 'anon : insertion directe refusée');
await db.exec(`reset role; set role authenticated; set app.uid='11111111-1111-1111-1111-111111111111'`);
const mine = (await db.query(`select distinct fiche_path from public.fiche_retours`)).rows.map(x => x.fiche_path); ok(mine.length === 1 && mine[0] === '/fiches/a-FINAL.html', 'agent 1 ne voit que les retours de ses fiches');
await db.exec(`delete from public.fiche_retours`); await db.exec(`reset role`);
ok(await count(`where fiche_path='/fiches/b-FINAL.html'`) === 40, 'retours de l\'agent 2 intacts');
await db.exec(sql); ok(true, 'script rejouable');
console.log(bad ? bad + ' échec(s)' : 'OK sql retours');
